export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE'

export const SET_SELECTED_INDEX = 'SET_SELECTED_INDEX'

export const CLEAR_ALERT = 'CLEAR_ALERT'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const GET_DRINKS_BEGIN = 'GET_DRINKS_BEGIN'
export const GET_DRINKS_SUCCESS = 'GET_DRINKS_SUCCESS'

export const INPUT_CHANGE = 'INPUT_CHANGE'

export const CLEAR_INPUT_VALUES = 'CLEAR_INPUT_VALUES'

export const POST_RECIPE_BEGIN = 'POST_RECIPE_BEGIN'
export const POST_RECIPE_SUCCESS = 'POST_RECIPE_SUCCESS'
export const POST_RECIPE_ERROR = 'POST_RECIPE_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const TOGGLE_LOGIN_MODAL = 'TOGGLE_LOGIN_MODAL'
